name: Run black
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install venv
        run: |
          sudo apt-get -y install python3.10-venv
      - uses: psf/black@stable
        with:
          options: "--check --verbose -l88"
          src: "./sgm ./scripts ./main.py"
